### ISSUE TITLE
Long Text Input Form

### ISSUE THREAD

**Issue by johnrees** [theopensystemslab/ripa#10]
![Screenshot 2020-01-23 at 10 55 33 AM](https://user-images.githubusercontent.com/601961/72978739-e6070b00-3dce-11ea-9beb-c01d9f3df331.png)

## TODO

- [x] Add `label`:string as an optional prop
- [x] Add `required`:boolean as optional prop (default true)
- [x] Add `placeholder`:string as optional prop
- [x] Add Formik support

### BONUS

- [x] Add `maxWords`:number as an optional prop
