### ISSUE TITLE
Short Text Input Form

### ISSUE THREAD

**Issue by johnrees** [theopensystemslab/ripa#11]
![Screenshot 2020-01-23 at 10 55 08 AM](https://user-images.githubusercontent.com/601961/72978697-d7b8ef00-3dce-11ea-83f5-f9b7154163d0.png)

https://github.com/theopensystemslab/planx-editor/blob/master/src/amira/Text.fixture.tsx

## TODO

- [x] Add `label`:string as an optional prop
- [x] Add `required`:boolean as optional prop (default true)
- [x] Add `placeholder`:string as optional prop
- [x]  Add Formik support
