### ISSUE TITLE
File Upload Form

### ISSUE THREAD

**Issue by johnrees** [theopensystemslab/ripa#5]
![Screenshot 2020-01-23 at 10 23 09 AM](https://user-images.githubusercontent.com/601961/72976393-73942c00-3dca-11ea-82b7-29e3332082ff.png)

Example

```jsx
<FileUploadForm title="New Title" accept={["image/*", ".pdf", ".doc", ".docx"]} maxSize={2e+7} />
```

HTML5 example here for reference https://github.com/theopensystemslab/planx-editor/blob/master/src/amira/FileUpload.fixture.tsx

Might be better to use https://github.com/react-dropzone/react-dropzone ?

## TODO

- [x] Make upload box clickable to open file dialogue and select files for upload
- [x] Save file info e.g. filename, size, filetype in local state for now

### BONUS

- [ ] Make uploads actually work, so that their URLs are saved with the filenames. I can set up an S3 bucket for the files if necessary
- [x] `maxSize` param: (in bytes) from https://react-dropzone.js.org/#!/Dropzone
- [x] `accept` param: https://react-dropzone.js.org/#!/Accepting%20specific%20file%20types
