### ISSUE TITLE
Email Address

### ISSUE THREAD

**Issue by johnrees** [theopensystemslab/ripa#8]
![Screenshot 2020-01-23 at 10 25 23 AM](https://user-images.githubusercontent.com/601961/72976528-ae965f80-3dca-11ea-9564-279ac3f033d2.png)

```jsx
<EmailAddressInput title="New Title" />
```
## TODO

- [x] Validate email address. Using html5 input `type="email"` would suffice
- [x] Add required as an optional prop
- [x] Add Formik support
