### ISSUE TITLE
Number Input Form

### ISSUE THREAD

**Issue by johnrees** [theopensystemslab/ripa#9]
![Screenshot 2020-01-23 at 10 34 07 AM](https://user-images.githubusercontent.com/601961/72977213-efdb3f00-3dcb-11ea-8d64-7e988ba30679.png)

Number input from https://material-ui.com/components/text-fields/

```jsx
<NumberInput title="Title" label="label" unit="m" />
```

## TODO

- [x] Add `unit`:string as an optional prop
- [x] Validate input is a number
- [x] Add Formik support

### BONUS

- [x] Add `max`:number and `min`:number as optional props
- [x] Validate input is within range of min and max if they are specified
